### ISSUE TITLE
formula erronea

### ISSUE THREAD

**Issue by Eugemo** [mnrios1997/CollatzConjeture#1]
en la linea 13 la expresion correcta deberia ser 
` c0 = int(c0 * 4 + 1)`

aclaracion: la formula es correcta, pero no se python :( y no sabria si la sintaxis es correcta o no, aparentemente la logica del condicional, hasta donde entiendo esta. opiniones?

**Comment by mnrios1997** [comment]
si, la lógica en realidad está bien, lo que si se puede hacer es utilizar otros operadores por ejemplo en la linea 14, cambiándola por steps += 1 directamente (ahorraría el tener que escribir la variable dos veces)

**Comment by Eugemo** [comment]
entonces ` steps = steps + 1` es igual a `steps +=1` ?
asigname y lo resuelvo con ese cambio en `line 8` y `line 14`

**Comment by mnrios1997** [comment]
Exactamente, es lo mismo, ya está asignado!
