### ISSUE TITLE
Modificar la impresión por pantalla para indicar valor y paso.

### ISSUE THREAD

**Issue by rmoyano** [mnrios1997/CollatzConjeture#5]
Puedo modificar la impresión por pantalla para indicar valor y número de step por cálculo:
print 'Valor: {0} - Paso: {1} '.format(c0, steps)

Así también detallar al final que es el total de pasos de realizados:
print 'Total de pasos: {0}.'.format(steps)

**Comment by mnrios1997** [comment]
Excelente, te asigné el issue
